# Generated by Django 4.0.4 on 2022-05-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='dueDate',
            field=models.TextField(),
        ),
    ]
