# Generated by Django 4.0.4 on 2022-05-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_alter_tasklist_created_alter_tasklist_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='dueDate',
            field=models.DateTimeField(),
        ),
    ]
